version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 80
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 3
  identical-code:
    config:
      threshold: 3
exclude_patterns:
  - "lib/foundation.js"
  - "**/test/*"
  - "**/dist/*"
  - "**/*.dist.js"
  - "**/templates/*"
  