version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 6
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 80
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 6
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 25
exclude_patterns:
  - "**/test/*"
  - "**/dist/*"
  - "**/*.dist.js"
  - "**/templates/*"
  