name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        First please check that this issue is not already solved as
        [described here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug)
  - type: checkboxes
    id: duplicate-box
    attributes:
      label: Contributing
      options:
        - label: I've searched and did not find any similar issues
          required: true
  - type: input
    id: repro-link
    attributes:
      label: Minimal Reproduction
      description: |
        If you can, please create a simple example that reproduces the issue and link to a gist, jsbin,
        repo, etc. This makes it much easier for us to debug and issues that have a reproducible example
        will get higher priority.
      placeholder: gist, jsbin, repo, CodeSandbox, Glitch, etc
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps we would need to take to reproduce the issue
      value: |
        1. Run npm start
        2. ...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what broke. The more detailed the better.
      placeholder: Tell us what you see!
      value: |
        Tell us what broke. The more detailed the better.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected
  - type: input
    id: version
    attributes:
      label: Feathers Version
      description: What version of Feathers are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Other
        - Does not apply
  - type: textarea
    id: sysconfig
    attributes:
      label: System Configuration
      description: Tell us about the applicable parts of your setup.
      render: markdown
      value: |
        **Module versions** (especially the part that's not working):  
        **NodeJS version**:  
        **Operating System**:  
        **Browser Version**:  
        **React Native Version**:  
        **Module Loader**:
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
