// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contributors: typeof import('./components/Contributors.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Tab: typeof import('./components/Tab.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TeamMember: typeof import('./components/TeamMember.vue')['default']
  }
}

export {}
