// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badges: typeof import('./components/Badges.vue')['default']
    BlockQuote: typeof import('./components/BlockQuote.vue')['default']
    Contributors: typeof import('./components/Contributors.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    LanguageBlock: typeof import('./components/LanguageBlock.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Tab: typeof import('./components/Tab.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TeamMember: typeof import('./components/TeamMember.vue')['default']
  }
}
