name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 24.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g npm
      # Removing node_modules and package-lock.json is a workaround for some Rollup on Linux bug
      - run: |
          rm -rf node_modules package-lock.json
          npm install
      - run: npm test
        env:
          CI: true
